spring:
  datasource:
    url: jdbc:h2:file:./data/h2/lmdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
server:
  port: 8082

logging:
  level:
    org:
      hibernate:
        SQL: off
        type:
          descriptor:
            sql:
              BasicBinder: off
